apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-yellow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-yellow
        image: name/nginx:yellow
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
