apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-red
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-red
        image: name/nginx:red
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
